export const ADD_QUESTION = 'ADD_QUESTION';
export const ADD_CHOICE = "ADD_CHOICE"
export const SHOW_SURVEYS = 'SHOW_SURVEYS';
export const CHANGE_QUESTION_TITLE = 'CHANGE_QUESTION_TITLE';
export const CHANGE_SURVEY_TITLE = 'CHANGE_SURVEY_TITLE';
export const DELETE_SURVEY = "DELETE_SURVEY";
export const DELETE_QUESTION = "DELETE_QUESTION";
export const DELETE_CHOICE = "DELETE_CHOICE"
export const PREVIEW_SURVEY = 'PREVIEW_SURVEY';
export const SUBMET_SURVEY = "SUBMET_SURVEY";
export const CHANGE_QUESTION_TYPE = 'CHANGE_QUESTION_TYPE';
export const CHANGE_CHOISE_LABEL = 'CHANGE_CHOISE_LABEL'
export const POST = "POST_TO_SERVER";
export const POST_FAILED = "POST_FAILED";

export const PREVIEW_REPORT = "PREVIEW_REPORT";
export const ANSWER_TEXT = 'ANSWER_TEXT';
export const ANSWER_MULTIPLE_CHOICE = 'ANSWER_MULTIPLE_CHOICE';
export const ANSWER_SINGLE_NUMBER_VALUE = 'ANSWER_SINGLE_NUMBER_VALUE';
export const ANSWER_RANGE = 'ANSWER_RANGE';

// mouaz was here 
export const chartsTypes = { ANSWER_TEXT: "bar", ANSWER_MULTIPLE_CHOICE: "pie", ANSWER_RANGE: "area", ANSWER_SINGLE_NUMBER_VALUE: "line" };

export const SUBMIT_NEW_SERVEY = 'SUBMIT_NEW_SERVEY';
export const CHANGE_LINEAR_CONTENT = 'CHANGE_LINEAR_CONTENT';
export const CHANGE_MIN_VALUE = 'CHANGE_MIN_VALUE';
export const CHANGE_MAX_VALUE = 'CHANGE_MAX_VALUE';
export const CHANGE_DEFAULT_VALUE = 'CHANGE_DEFAULT_VALUE';
export const CHANGE_STEP_VALUE = 'CHANGE_STEP_VALUE';
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const CURRENT_USER = "CURRENT_USER";
export const LOAD_RESPONSES_LIST = "LOAD_RESPONSES_LIST";
export const LOAD_RESPONSE = "LOAD_RESPONSE";
export const CHANGE_BG = "CHANGE_BG";